name: CI

# Controls when the workflow will run - Manual
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Azure Login
        uses: Azure/login@v1.4.1
        with: # Set Azure credentials secret as an input
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI Action - Create Backend
        uses: Azure/cli@v1.0.6
        with:
          # Specify the script here
          inlineScript: |
            $RESOURCE_GROUP_NAME = "tfstate-rg"
            $STORAGE_ACCOUNT_NAME = "terraformstate2345"
            
            $CONTAINER_NAME = "terraformstate"
          
            $AZRM_BACKENDKV_NAME = "AzureRMBackendKV"
            
            $TF_RG_SECRET_NAME = "tfrgname-secret"
            $TF_STORAGEACC_SECRET_NAME = "tfstorageaccname-secret"
            $TF_ACCOUNTKEY_SECRET_NAME = "tfstorageacckey-secret"
            $TF_CONTAINER_SECRET_NAME = "tfcontainer-secret"

            # Create resource group
            az group create --name $RESOURCE_GROUP_NAME --location eastus2
            
            # Create storage account
            az storage account create --resource-group $RESOURCE_GROUP_NAME --name $STORAGE_ACCOUNT_NAME --sku Standard_LRS --encryption-services blob
            
            # Get storage account key
            $ACCOUNT_KEY = $(az storage account keys list --resource-group $RESOURCE_GROUP_NAME --account-name $STORAGE_ACCOUNT_NAME --query [0].value -o tsv)
            
            # Create blob container
            az storage container create --name $CONTAINER_NAME --account-name $STORAGE_ACCOUNT_NAME --account-key $ACCOUNT_KEY
            
            # Create a new key vault
            az keyvault create --name $AZRM_BACKENDKV_NAME --resource-group $RESOURCE_GROUP_NAME
            
            # Create a new key vault secret with $RESOURCE_GROUP_NAME
            az keyvault secret set --name $TF_RG_SECRET_NAME --value $RESOURCE_GROUP_NAME --vault-name $AZRM_BACKENDKV_NAME

            # Create a new key vault secret with $STORAGE_ACCOUNT_NAME
            az keyvault secret set --name $TF_STORAGEACC_SECRET_NAME --value $STORAGE_ACCOUNT_NAME --vault-name $AZRM_BACKENDKV_NAME

            # Create a new key vault secret with $CONTAINER_NAME
            az keyvault secret set --name $TF_CONTAINER_SECRET_NAME --value $CONTAINER_NAME --vault-name $AZRM_BACKENDKV_NAME

            # Create a new key vault secret with $ACCOUNTKEY
            az keyvault secret set --name $TF_ACCOUNTKEY_SECRET_NAME --value $ACCOUNT_KEY --vault-name $AZRM_BACKENDKV_NAME
            
            Write-Host "resource_group_name: $RESOURCE_GROUP_NAME"
            Write-Host "storage_account_name: $STORAGE_ACCOUNT_NAME"
            Write-Host "container_name: $CONTAINER_NAME"


